"""Add avatar_url to users

Revision ID: 218c8555cd6a
Revises: 5cb50b8e66ce
Create Date: 2026-09-14 10:02:35.324295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218c8555cd6a'
down_revision = '5cb50b8e66ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
